server:
  port: 3000

# 该配置的名称是固定的，不可以改变，否则将不能自动加载到数据源中
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/incubator?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zdl.**.entities
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    com:
      zdl:
        lottery:
          mapper: DEBUG
  file:
    # spring.log 输出路径
    path: log/
  # 日志输出格式说明:
  # %d 输出日期时间，
  # %thread 输出当前线程名，
  # %-5level 输出日志级别，左对齐5个字符宽度
  # %logger{50} 输出全类名最长50个字符，超过按照句点分割
  # %msg 日志信息
  # %n 换行符
  pattern:
    # 修改控制台输出的日志格式
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
    # 修改文件中输出的日志格式
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n'
debug: true
